# Generated by Django 5.2 on 2025-05-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gst',
            options={'ordering': ['gst_percentage']},
        ),
        migrations.AlterUniqueTogether(
            name='gst',
            unique_together={('gst_percentage',)},
        ),
    ]
