# Generated by Django 5.2 on 2025-05-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulemaster', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='users', to='modulemaster.modulemaster'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
