# Generated by Django 5.2 on 2025-05-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_permissions_user_modules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modules',
        ),
    ]
