# Generated by Django 5.2 on 2025-05-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_alter_user_options_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '4. Users'},
        ),
    ]
