# Generated by Django 5.2 on 2025-05-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_types', '0002_alter_userprofile_user_type'),
        ('users', '0003_remove_user_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user_types.userprofile'),
        ),
    ]
