# Generated by Django 5.2 on 2025-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_permission_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.AddField(
            model_name='permission',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='model_name',
            field=models.CharField(choices=[('organization', 'Organization'), ('department', 'Department'), ('team', 'Team')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
