# Generated by Django 5.2 on 2025-05-09 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0002_alter_district_options'),
        ('package', '0002_alter_package_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=255)),
                ('block_code', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='district.district')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='package.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
