# Generated by Django 5.2 on 2025-05-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0002_alter_district_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('Project', 'Project'), ('O&M', 'O&M')], max_length=20)),
                ('zone_type', models.CharField(choices=[('Zonal', 'Zonal'), ('District', 'District')], max_length=20)),
                ('assigned_user', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('contact_persons', models.JSONField(default=list)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('capacity', models.CharField(max_length=50)),
                ('gps_coordinates', models.JSONField(blank=True, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.district')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'ordering': ['warehouse_name'],
                'unique_together': {('warehouse_name', 'warehouse_type')},
            },
        ),
    ]
