# Generated by Django 5.2 on 2025-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
