# Generated by Django 5.2 on 2025-05-02 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('organisation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('organisation_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('industry_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Organizations',
            },
        ),
    ]
