# Generated by Django 5.2 on 2025-05-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='status',
        ),
    ]
