# Generated by Django 5.2 on 2025-05-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_create_organization', 'Can create organization'), ('can_edit_mobile', 'Can edit mobile number')], 'verbose_name_plural': '1. Organizations'},
        ),
    ]
