# Generated by Django 5.2 on 2025-05-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': '1. Organizations'},
        ),
    ]
