# Generated by Django 5.2 on 2025-05-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_read_organization', 'Can read organization'), ('can_create_organization', 'Can create organization'), ('can_update_organization', 'Can update organization'), ('can_delete_organization', 'Can delete organization')], 'verbose_name_plural': '1. Organizations'},
        ),
    ]
