# Generated by Django 5.2 on 2025-05-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name',)},
        ),
    ]
