# Generated by Django 5.2 on 2025-05-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_unique_together'),
        ('hsn', '0001_initial'),
        ('subcategory', '0001_initial'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('material_name', models.CharField(max_length=255, unique=True)),
                ('material_code', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('SOR', 'SOR'), ('NONSOR', 'NONSOR')], max_length=16)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('gst_hsn_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsn.hsncode')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory')),
                ('uom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uom.uom')),
            ],
            options={
                'verbose_name': 'Material',
                'ordering': ['material_name'],
                'unique_together': {('material_name', 'material_code')},
            },
        ),
    ]
