# Generated by Django 5.2 on 2025-05-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('onboarding_date', models.DateField()),
                ('pan_no', models.CharField(max_length=20)),
                ('gst_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('kyc_complaints', models.TextField(blank=True, null=True)),
                ('branch_details', models.TextField(blank=True, null=True)),
                ('material_details', models.TextField(blank=True, null=True)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='uploads/pan_files/')),
                ('gst_file', models.FileField(blank=True, null=True, upload_to='uploads/gst_files/')),
            ],
            options={
                'verbose_name_plural': '1. Suppliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
