# Generated by Django 5.2 on 2025-05-09 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0002_alter_package_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
                ('district_code', models.CharField(max_length=100, unique=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='package.package')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['-created_at'],
            },
        ),
    ]
