# Generated by Django 5.2 on 2025-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Supervisor', 'Supervisor'), ('Director', 'Director'), ('Employee', 'Employee')], max_length=20),
        ),
    ]
